steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/ecomate-ai-service
      - -f
      - Dockerfile
      - .
images:
  - gcr.io/$PROJECT_ID/ecomate-ai-service
