// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: product_analysis.proto

package product_analysis

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ProductAnalysisService_AnalyzeProduct_FullMethodName     = "/product_analysis.ProductAnalysisService/AnalyzeProduct"
	ProductAnalysisService_CalculateCO2Impact_FullMethodName = "/product_analysis.ProductAnalysisService/CalculateCO2Impact"
)

// ProductAnalysisServiceClient is the client API for ProductAnalysisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductAnalysisServiceClient interface {
	AnalyzeProduct(ctx context.Context, in *AnalyzeProductRequest, opts ...grpc.CallOption) (*AnalyzeProductResponse, error)
	CalculateCO2Impact(ctx context.Context, in *CalculateCO2Request, opts ...grpc.CallOption) (*CalculateCO2Response, error)
}

type productAnalysisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductAnalysisServiceClient(cc grpc.ClientConnInterface) ProductAnalysisServiceClient {
	return &productAnalysisServiceClient{cc}
}

func (c *productAnalysisServiceClient) AnalyzeProduct(ctx context.Context, in *AnalyzeProductRequest, opts ...grpc.CallOption) (*AnalyzeProductResponse, error) {
	out := new(AnalyzeProductResponse)
	err := c.cc.Invoke(ctx, ProductAnalysisService_AnalyzeProduct_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productAnalysisServiceClient) CalculateCO2Impact(ctx context.Context, in *CalculateCO2Request, opts ...grpc.CallOption) (*CalculateCO2Response, error) {
	out := new(CalculateCO2Response)
	err := c.cc.Invoke(ctx, ProductAnalysisService_CalculateCO2Impact_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductAnalysisServiceServer is the server API for ProductAnalysisService service.
// All implementations must embed UnimplementedProductAnalysisServiceServer
// for forward compatibility
type ProductAnalysisServiceServer interface {
	AnalyzeProduct(context.Context, *AnalyzeProductRequest) (*AnalyzeProductResponse, error)
	CalculateCO2Impact(context.Context, *CalculateCO2Request) (*CalculateCO2Response, error)
	mustEmbedUnimplementedProductAnalysisServiceServer()
}

// UnimplementedProductAnalysisServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProductAnalysisServiceServer struct {
}

func (UnimplementedProductAnalysisServiceServer) AnalyzeProduct(context.Context, *AnalyzeProductRequest) (*AnalyzeProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeProduct not implemented")
}
func (UnimplementedProductAnalysisServiceServer) CalculateCO2Impact(context.Context, *CalculateCO2Request) (*CalculateCO2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateCO2Impact not implemented")
}
func (UnimplementedProductAnalysisServiceServer) mustEmbedUnimplementedProductAnalysisServiceServer() {
}

// UnsafeProductAnalysisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductAnalysisServiceServer will
// result in compilation errors.
type UnsafeProductAnalysisServiceServer interface {
	mustEmbedUnimplementedProductAnalysisServiceServer()
}

func RegisterProductAnalysisServiceServer(s grpc.ServiceRegistrar, srv ProductAnalysisServiceServer) {
	s.RegisterService(&ProductAnalysisService_ServiceDesc, srv)
}

func _ProductAnalysisService_AnalyzeProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductAnalysisServiceServer).AnalyzeProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductAnalysisService_AnalyzeProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductAnalysisServiceServer).AnalyzeProduct(ctx, req.(*AnalyzeProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductAnalysisService_CalculateCO2Impact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateCO2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductAnalysisServiceServer).CalculateCO2Impact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductAnalysisService_CalculateCO2Impact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductAnalysisServiceServer).CalculateCO2Impact(ctx, req.(*CalculateCO2Request))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductAnalysisService_ServiceDesc is the grpc.ServiceDesc for ProductAnalysisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductAnalysisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product_analysis.ProductAnalysisService",
	HandlerType: (*ProductAnalysisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeProduct",
			Handler:    _ProductAnalysisService_AnalyzeProduct_Handler,
		},
		{
			MethodName: "CalculateCO2Impact",
			Handler:    _ProductAnalysisService_CalculateCO2Impact_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product_analysis.proto",
}
