// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.3
// source: product_analysis.proto

package product_analysis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeProductRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Images                  [][]byte               `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	Title                   string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	UserProvidedDescription string                 `protobuf:"bytes,3,opt,name=user_provided_description,json=userProvidedDescription,proto3" json:"user_provided_description,omitempty"`
	Category                string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AnalyzeProductRequest) Reset() {
	*x = AnalyzeProductRequest{}
	mi := &file_product_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeProductRequest) ProtoMessage() {}

func (x *AnalyzeProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeProductRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeProductRequest) Descriptor() ([]byte, []int) {
	return file_product_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeProductRequest) GetImages() [][]byte {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *AnalyzeProductRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AnalyzeProductRequest) GetUserProvidedDescription() string {
	if x != nil {
		return x.UserProvidedDescription
	}
	return ""
}

func (x *AnalyzeProductRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type AnalyzeProductResponse struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	GeneratedDescription       string                 `protobuf:"bytes,1,opt,name=generated_description,json=generatedDescription,proto3" json:"generated_description,omitempty"`
	SuggestedPrice             int32                  `protobuf:"varint,2,opt,name=suggested_price,json=suggestedPrice,proto3" json:"suggested_price,omitempty"`
	EstimatedWeightKg          float32                `protobuf:"fixed32,3,opt,name=estimated_weight_kg,json=estimatedWeightKg,proto3" json:"estimated_weight_kg,omitempty"`
	ManufacturerCountry        string                 `protobuf:"bytes,4,opt,name=manufacturer_country,json=manufacturerCountry,proto3" json:"manufacturer_country,omitempty"`
	EstimatedManufacturingYear int32                  `protobuf:"varint,5,opt,name=estimated_manufacturing_year,json=estimatedManufacturingYear,proto3" json:"estimated_manufacturing_year,omitempty"`
	Co2ImpactKg                float32                `protobuf:"fixed32,6,opt,name=co2_impact_kg,json=co2ImpactKg,proto3" json:"co2_impact_kg,omitempty"`
	IsInappropriate            bool                   `protobuf:"varint,7,opt,name=is_inappropriate,json=isInappropriate,proto3" json:"is_inappropriate,omitempty"`
	InappropriateReason        string                 `protobuf:"bytes,8,opt,name=inappropriate_reason,json=inappropriateReason,proto3" json:"inappropriate_reason,omitempty"`
	DetectedObjects            []string               `protobuf:"bytes,9,rep,name=detected_objects,json=detectedObjects,proto3" json:"detected_objects,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *AnalyzeProductResponse) Reset() {
	*x = AnalyzeProductResponse{}
	mi := &file_product_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeProductResponse) ProtoMessage() {}

func (x *AnalyzeProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeProductResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeProductResponse) Descriptor() ([]byte, []int) {
	return file_product_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeProductResponse) GetGeneratedDescription() string {
	if x != nil {
		return x.GeneratedDescription
	}
	return ""
}

func (x *AnalyzeProductResponse) GetSuggestedPrice() int32 {
	if x != nil {
		return x.SuggestedPrice
	}
	return 0
}

func (x *AnalyzeProductResponse) GetEstimatedWeightKg() float32 {
	if x != nil {
		return x.EstimatedWeightKg
	}
	return 0
}

func (x *AnalyzeProductResponse) GetManufacturerCountry() string {
	if x != nil {
		return x.ManufacturerCountry
	}
	return ""
}

func (x *AnalyzeProductResponse) GetEstimatedManufacturingYear() int32 {
	if x != nil {
		return x.EstimatedManufacturingYear
	}
	return 0
}

func (x *AnalyzeProductResponse) GetCo2ImpactKg() float32 {
	if x != nil {
		return x.Co2ImpactKg
	}
	return 0
}

func (x *AnalyzeProductResponse) GetIsInappropriate() bool {
	if x != nil {
		return x.IsInappropriate
	}
	return false
}

func (x *AnalyzeProductResponse) GetInappropriateReason() string {
	if x != nil {
		return x.InappropriateReason
	}
	return ""
}

func (x *AnalyzeProductResponse) GetDetectedObjects() []string {
	if x != nil {
		return x.DetectedObjects
	}
	return nil
}

type CalculateCO2Request struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Category            string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	WeightKg            float32                `protobuf:"fixed32,2,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	ManufacturerCountry string                 `protobuf:"bytes,3,opt,name=manufacturer_country,json=manufacturerCountry,proto3" json:"manufacturer_country,omitempty"`
	ManufacturingYear   int32                  `protobuf:"varint,4,opt,name=manufacturing_year,json=manufacturingYear,proto3" json:"manufacturing_year,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CalculateCO2Request) Reset() {
	*x = CalculateCO2Request{}
	mi := &file_product_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateCO2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateCO2Request) ProtoMessage() {}

func (x *CalculateCO2Request) ProtoReflect() protoreflect.Message {
	mi := &file_product_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateCO2Request.ProtoReflect.Descriptor instead.
func (*CalculateCO2Request) Descriptor() ([]byte, []int) {
	return file_product_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *CalculateCO2Request) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CalculateCO2Request) GetWeightKg() float32 {
	if x != nil {
		return x.WeightKg
	}
	return 0
}

func (x *CalculateCO2Request) GetManufacturerCountry() string {
	if x != nil {
		return x.ManufacturerCountry
	}
	return ""
}

func (x *CalculateCO2Request) GetManufacturingYear() int32 {
	if x != nil {
		return x.ManufacturingYear
	}
	return 0
}

type CalculateCO2Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuyingNewKg   float32                `protobuf:"fixed32,1,opt,name=buying_new_kg,json=buyingNewKg,proto3" json:"buying_new_kg,omitempty"`
	BuyingUsedKg  float32                `protobuf:"fixed32,2,opt,name=buying_used_kg,json=buyingUsedKg,proto3" json:"buying_used_kg,omitempty"`
	SavedKg       float32                `protobuf:"fixed32,3,opt,name=saved_kg,json=savedKg,proto3" json:"saved_kg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateCO2Response) Reset() {
	*x = CalculateCO2Response{}
	mi := &file_product_analysis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateCO2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateCO2Response) ProtoMessage() {}

func (x *CalculateCO2Response) ProtoReflect() protoreflect.Message {
	mi := &file_product_analysis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateCO2Response.ProtoReflect.Descriptor instead.
func (*CalculateCO2Response) Descriptor() ([]byte, []int) {
	return file_product_analysis_proto_rawDescGZIP(), []int{3}
}

func (x *CalculateCO2Response) GetBuyingNewKg() float32 {
	if x != nil {
		return x.BuyingNewKg
	}
	return 0
}

func (x *CalculateCO2Response) GetBuyingUsedKg() float32 {
	if x != nil {
		return x.BuyingUsedKg
	}
	return 0
}

func (x *CalculateCO2Response) GetSavedKg() float32 {
	if x != nil {
		return x.SavedKg
	}
	return 0
}

var File_product_analysis_proto protoreflect.FileDescriptor

const file_product_analysis_proto_rawDesc = "" +
	"\n" +
	"\x16product_analysis.proto\x12\x10product_analysis\"\x9d\x01\n" +
	"\x15AnalyzeProductRequest\x12\x16\n" +
	"\x06images\x18\x01 \x03(\fR\x06images\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12:\n" +
	"\x19user_provided_description\x18\x03 \x01(\tR\x17userProvidedDescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\"\xc8\x03\n" +
	"\x16AnalyzeProductResponse\x123\n" +
	"\x15generated_description\x18\x01 \x01(\tR\x14generatedDescription\x12'\n" +
	"\x0fsuggested_price\x18\x02 \x01(\x05R\x0esuggestedPrice\x12.\n" +
	"\x13estimated_weight_kg\x18\x03 \x01(\x02R\x11estimatedWeightKg\x121\n" +
	"\x14manufacturer_country\x18\x04 \x01(\tR\x13manufacturerCountry\x12@\n" +
	"\x1cestimated_manufacturing_year\x18\x05 \x01(\x05R\x1aestimatedManufacturingYear\x12\"\n" +
	"\rco2_impact_kg\x18\x06 \x01(\x02R\vco2ImpactKg\x12)\n" +
	"\x10is_inappropriate\x18\a \x01(\bR\x0fisInappropriate\x121\n" +
	"\x14inappropriate_reason\x18\b \x01(\tR\x13inappropriateReason\x12)\n" +
	"\x10detected_objects\x18\t \x03(\tR\x0fdetectedObjects\"\xb0\x01\n" +
	"\x13CalculateCO2Request\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x1b\n" +
	"\tweight_kg\x18\x02 \x01(\x02R\bweightKg\x121\n" +
	"\x14manufacturer_country\x18\x03 \x01(\tR\x13manufacturerCountry\x12-\n" +
	"\x12manufacturing_year\x18\x04 \x01(\x05R\x11manufacturingYear\"{\n" +
	"\x14CalculateCO2Response\x12\"\n" +
	"\rbuying_new_kg\x18\x01 \x01(\x02R\vbuyingNewKg\x12$\n" +
	"\x0ebuying_used_kg\x18\x02 \x01(\x02R\fbuyingUsedKg\x12\x19\n" +
	"\bsaved_kg\x18\x03 \x01(\x02R\asavedKg2\xe2\x01\n" +
	"\x16ProductAnalysisService\x12c\n" +
	"\x0eAnalyzeProduct\x12'.product_analysis.AnalyzeProductRequest\x1a(.product_analysis.AnalyzeProductResponse\x12c\n" +
	"\x12CalculateCO2Impact\x12%.product_analysis.CalculateCO2Request\x1a&.product_analysis.CalculateCO2ResponseB8Z6github.com/yourusername/ecomate/proto;product_analysisb\x06proto3"

var (
	file_product_analysis_proto_rawDescOnce sync.Once
	file_product_analysis_proto_rawDescData []byte
)

func file_product_analysis_proto_rawDescGZIP() []byte {
	file_product_analysis_proto_rawDescOnce.Do(func() {
		file_product_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_analysis_proto_rawDesc), len(file_product_analysis_proto_rawDesc)))
	})
	return file_product_analysis_proto_rawDescData
}

var file_product_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_product_analysis_proto_goTypes = []any{
	(*AnalyzeProductRequest)(nil),  // 0: product_analysis.AnalyzeProductRequest
	(*AnalyzeProductResponse)(nil), // 1: product_analysis.AnalyzeProductResponse
	(*CalculateCO2Request)(nil),    // 2: product_analysis.CalculateCO2Request
	(*CalculateCO2Response)(nil),   // 3: product_analysis.CalculateCO2Response
}
var file_product_analysis_proto_depIdxs = []int32{
	0, // 0: product_analysis.ProductAnalysisService.AnalyzeProduct:input_type -> product_analysis.AnalyzeProductRequest
	2, // 1: product_analysis.ProductAnalysisService.CalculateCO2Impact:input_type -> product_analysis.CalculateCO2Request
	1, // 2: product_analysis.ProductAnalysisService.AnalyzeProduct:output_type -> product_analysis.AnalyzeProductResponse
	3, // 3: product_analysis.ProductAnalysisService.CalculateCO2Impact:output_type -> product_analysis.CalculateCO2Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_product_analysis_proto_init() }
func file_product_analysis_proto_init() {
	if File_product_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_analysis_proto_rawDesc), len(file_product_analysis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_analysis_proto_goTypes,
		DependencyIndexes: file_product_analysis_proto_depIdxs,
		MessageInfos:      file_product_analysis_proto_msgTypes,
	}.Build()
	File_product_analysis_proto = out.File
	file_product_analysis_proto_goTypes = nil
	file_product_analysis_proto_depIdxs = nil
}
